---
baseurl: "https://padloc.app/"
title: "Padloc - A Modern Password Manager For Individuals And Teams"
languageCode: "en-us"
metaDataFormat: "yaml"
pluralizelisttitles: false
ignoreFiles: "archive/*"
params:
    get_started_url: /#plans
    login_url: https://web.padloc.app
    security_whitepaper_url: https://github.com/padloc/padloc/blob/master/security.md
    github_url: https://github.com/padloc/padloc

    stripePublicKey: ""

    downloads:
        - title: Padloc for Mac
          type: desktop
          icon: apple
          url: https://github.com/padloc/padloc/releases/download/v3.1.3/Padloc-3.1.3.dmg
          version: 3.1.3
        - title: Padloc for Windows
          type: desktop
          icon: windows
          url: https://github.com/padloc/padloc/releases/download/v3.1.3/Padloc-Setup-3.1.3.exe
          version: 3.1.3
        - title: Padloc for Linux
          type: desktop
          icon: linux
          url: https://github.com/padloc/padloc/releases/download/v3.1.3/Padloc-3.1.3.AppImage
          version: 3.1.3
        - title: ChromeOS (Coming Soon)
          type: desktop
          icon: chrome
          url:
          version: 3.1.3
        - title: Padloc for iOS
          type: mobile
          icon: apple
          url: https://itunes.apple.com/app/id1478877043
          version: 3.1.3
        - title: Padloc for Android
          type: mobile
          icon: android
          url: https://play.google.com/store/apps/details?id=app.padloc
          version: 3.1.3
        - title: Google Chrome
          type: extension
          icon: chrome
          url: https://chrome.google.com/webstore/detail/padloc/bjpblhcipjjiobljnniifeoaapgdflnc
          version: 3.1.3
        - title: Firefox
          type: extension
          icon: firefox
          url: https://addons.mozilla.org/en-US/firefox/addon/padloc/
          version: 3.1.3

    downloads_v2:
        - title: Padloc for Mac
          type: desktop
          icon: apple
          url: https://github.com/padloc/padloc/releases/download/v2.7.2/padlock-2.7.2.dmg
          version: 2.7.2
        - title: Padloc for Windows
          type: desktop
          icon: windows
          url: https://github.com/padloc/padloc/releases/download/v2.7.2/padlock-setup-2.7.2.exe
          version: 2.7.2
        - title: Padloc for Linux
          type: desktop
          icon: linux
          url: https://github.com/padloc/padloc/releases/download/v2.7.2/padlock-2.7.2-x86_64.AppImage
          version: 2.7.2
        - title: Padloc for ChromeOS
          type: desktop
          icon: chrome
          url: https://chrome.google.com/webstore/detail/padlock/npkoefjfcjbknoeadfkbcdpbapaamcif
          version: 2.7.2
        - title: Padloc for iOS
          type: mobile
          icon: apple
          url: https://itunes.apple.com/app/id871710139
          version: 2.7.2
        - title: Padloc for Android
          type: mobile
          icon: android
          url: https://play.google.com/store/apps/details?id=com.maklesoft.padlock
          version: 2.7.2

    productHuntUrl: https://www.producthunt.com/posts/padlock-2
    githubUrl: https://github.com/padloc/padloc/
    twitterUrl: https://twitter.com/padlocapp/
    mailchimpSignupUrl: https://maklesoft.us3.list-manage.com/subscribe/post?u=156fa42cf0f141436c20b06b2&amp;id=58a9450e8b

    plans:
        free:
            name: Free
            description: All basic features and up to 50 items for free.
            button_label: Get Started
            link: https://web.padloc.app/signup
            color_fg: "#444"
            color_bg: "#eee"
            features:
                - Store up to 50 passwords, credit cards and other items
                - Up to 2 connected devices
                - Free Apps for Mac, iOS, Windows, Android, Linux, and Chrome OS
                - Fast and easy access to your passwords through your browser
                - Free forever.
        premium:
            name: Premium
            description: Everything you need to secure your data online.
            price:
                dollars: 2
                cents: 99
            link: https://web.padloc.app/signup?next=plan%2F1
            color_fg: "#fff"
            color_bg: "#23b4ff"
            features:
                - Store unlimited passwords, credit cards and other data
                - Unlimited connected devices
                - 1GB of encrypted file storage
                - Free Apps for Mac, iOS, Windows, Android, Linux, and Chrome OS
                - Fast and easy access to your passwords through your browser
                - Advanced features like two-factor authentication and more!
        family:
            name: Family
            description: Simple and secure data storage for the entire family.
            price:
                dollars: 0
                cents: 99
            link: https://web.padloc.app/signup?next=plan%2F2
            color_fg: "#fff"
            color_bg: "#ff6666"
            features:
                - Securely share passwords, credit cards and other data
                - Easily manage what family members can see and do
                - 1GB of encrypted file storage
                - Free Apps for Mac, iOS, Windows, Android, Linux, and Chrome OS
                - Fast and easy access to your passwords through your browser
        team:
            name: Teams
            description: Simple and secure data storage for your team.
            price:
                dollars: 2
                cents: 99
            link: https://web.padloc.app/signup?next=plan%2F3
            color_fg: "#fff"
            color_bg: "#23b4ff"
            features:
                - Securely share passwords, documents, access keys and more
                - Up to 20 shared vaults with unlimited items
                - Up to 10 user groups for finegrained access control
                - 5GB of encrypted file storage
                - Free Apps for Mac, iOS, Windows, Android, Linux, and Chrome OS
                - Fast and easy data access through our web interface
        business:
            name: Business
            description: Flexibility and control for your advanced business needs.
            price:
                dollars: 5
                cents: 99
            link: https://web.padloc.app/signup?next=plan%2F4
            color_fg: "#fff"
            color_bg: "#ff6666"
            features:
                - Securely share passwords, documents, access keys and more
                - Unlimited shared vaults with unlimited items
                - Unlimited user groups for finegrained access control
                - 20GB of encrypted file storage
                - Free Apps for Mac, iOS, Windows, Android, Linux, and Chrome OS
                - Fast and easy data access through our web interface
                - 24/7 VIP support
        enterprise:
            name: Enterprise
            description: >-
                Industry-leading secure data management solution for
                organizations of any size.
            button_label: Get Custom Quote
            link: mailto:sales@padloc.app?title=Padloc+Enterprise
            color_fg: "#fff"
            color_bg: "#444"
            features:
                - Tailormade setup and training
                - 24/7 VIP support and dedicated account manager
                - Dedicated onboarding engineer for custom system integrations
                - Advanced tools for administration an monitoring
                - Hosted and on-premise options available
